val issue_dir : unit -> Path.t
val list : unit -> unit
val open_issue : unit -> unit
val edit : string -> unit
val search : string -> unit
val status : unit -> unit
val show : string -> unit
val html : unit -> unit
val validate : unit -> unit
